### PR TITLE
Auto build image in GitHub

### PR DESCRIPTION
**Pull request by digininja**
GitHub will now automatically build the image so I've updated the README to use this image rather than build it locally.

### CODE REVIEW

**Comment by digininja** [comment]
@loris-intergalactique Can you have a quick look at this and sanity check it.

I've got GitHub automatically building the image so I've updated your instructions so it pulls the image from the repo rather than building it locally. It seems to work for me but this is only the second time I've done this so not 100% sure if it is the right way to do things.

**Review by loris-intergalactique — CHANGES_REQUESTED** [review]
I think here we should chose to either explain people how to build it, and/or explain people how to use the `ghcr.io/digininja/cewl` image.

If you want to keep the building instructions, this section can stay as it is because it is correct (changing it with compose is not technically locally building it, and overkill) and we can add another section about using `ghcr.io/digininja/cewl`.

If you don't really want to keep the build instruction, we can change the whole content of this to "just use `docker run -it --rm ghcr.io/digininja/cewl http://dvwa.test`".

Personally, I think it is not our job to educate people on how to use docker, so we can just add one or two docker run lines. The one explaining how to use volumes is mostly here for script kiddies. We do not need the compose.yml file.

Do you want me to make a PR to do this change?

**Comment by digininja** [comment]
I should have known there would be a better way to do it!

Go for the PR and I'll see how you do it.

**Comment by loris-intergalactique** [comment]
Can be replaced by https://github.com/digininja/CeWL/pull/114

**Comment by digininja** [comment]
Boo, what fool wrote this, rejecting it.

**Comment by loris-intergalactique** [comment]
Hahahaha

**Pull request closed without merging**
