### PR TITLE
Not checking port and scheme

### PR DESCRIPTION
**Pull request by g0tmi1k**
My main reason for doing this, was because it wasn't checking to see if the port matched (it was only comparing the hosts) - 55854e4f702c204f59ae819a9d9a6ef670848b61
_I've also got it checking the scheme now too._

## Setup

```bash
[root:/tmp/www]# echo '<a href="http://localhost:123/test1">link1</a>' > index.html 
[root:/tmp/www]# echo '<a href="http://localhost:222/test2">link2</a>' >> index.html 
[root:/tmp/www]# echo '<a href="https://localhost:123/test3">link3</a>' >> index.html
[root:/tmp/www]# python2 -m SimpleHTTPServer 123 
Serving HTTP on 0.0.0.0 port 123 ...
```

- - -

## Before

The program crashes out before making a list

```
[root:~/CeWL]# ./cewl.rb localhost:123 
CeWL 5.1 Robin Wood (robin@digi.ninja) (https://digi.ninja/)

Unable to connect to the site (/test2)
Run in verbose mode (-v) for more information

[root:~/CeWL]#
```

- - -

## After

It's able to complete!

```
[root:~/CeWL]# ./cewl.rb localhost:123
CeWL 5.1 Robin Wood (robin@digi.ninja) (https://digi.ninja/)
link
[root:~/CeWL]# 
```

### CODE REVIEW

**Comment by g0tmi1k** [comment]
If this is accepted, would it be possible to get a tag'd release?

Not sure if you are ware, but there isn't a link on the homepage (https://digi.ninja/projects/cewl.php) to this Github repo...

**Comment by digininja** [comment]
I'll have a look through and test it out as soon as I get chance, if I've not done it in the next week or so, prod me.

What have you got against tabs? I prefer them as it lets everyone set their own indentation depth in their editor, I work to 4 spaces for mine.

**Comment by g0tmi1k** [comment]
Sure thing! Going to try and find some time after bsideslondon for another idea I want to add to it.

The tab thing - because of being told its Rails coding standards (https://stackoverflow.com/questions/6741586/rails-coding-standards-why-2-space-indentation), as well as anything I do for Metasploit....
And using tabs in RubyMine just made it very hard to read.

**Comment by digininja** [comment]
We should talk at BSides as I've got some ideas as well. The main one is that I would love to rip out the spider gem that is in there and replace it with a decent one but it would be quite a bit of work

**Comment by g0tmi1k** [comment]
Works for me ;) Will try and hunt for ya!

That sounds over my ruby skill set =(

**Comment by digininja** [comment]
I've seen your ruby skill set, it is way higher than you think it is!

**Comment by g0tmi1k** [comment]
@digininja contacted me privately asking me to use another branch (some_chaos_release) as the starting point
Closing #4, opening #5.

**Pull request closed without merging**
